android:
  - any: [ 'android/**/*','android/*' ]
ios:
  - any: [ 'ios/**/*','ios/*' ]
web:
  - any: [ 'web/**/*','web/*' ]
MAIN CHANGED!!!:
  - all: [ 'lib/main.dart']
target_changed:
  - all: [ 'lib/targets/*']