- name: "ios"
  color: "000000"
  description: "IOS folder changed"
- name: "android"
  color: "32CD32"
  description: "Android folder changed"
- name: "web"
  color: "FF00FF"
  description: "Web folder changed"
- name: "fix"
  color: "F4A460"
- name: "feature"
  color: "4682B4"
- name: "MAIN CHANGED!!!"
  color: "CC0000"
  description: "any target files have changes"