- name: "ios"
  color: "000000"
  description: "IOS folder changed"
- name: "android"
  color: "32CD32"
  description: "Android folder changed"
- name: "web"
  color: "FF00FF"
  description: "Web folder changed"
- name: "fix"
  color: "F4A460"
- name: "feature"
  color: "4682B4"
- name: "main_changed"
  color: "CC0000"
  description: "any target files have changes"
- name: "XS"
  color: "BFDADC"
  description: "<10"
- name: "S"
  color: "C2E0C6"
  description: "<100"
- name: "M"
  color: "FEF2C0"
  description: "<500"
- name: "L"
  color: "F9D0C4"
  description: "<1000"
- name: "XL"
  color: "E99695"
  description: ">1000"
