name: Assamble android
on:
  workflow_call:
    inputs:
      build_type:
        description: 'apk or appbundle'
        required: true
        type: string
        default: apk
      build_flavor:
        description: 'prod or dev'
        required: true
        type: string
        default: prod
jobs:
  build:
    name: Build prod ${{ inputs.build_type }}
    runs-on: [ self-hosted ]
    steps:
#      - name: Decrypt Android keys
#        run: sh ./.github/scripts/android/decrypt_android_keys.sh
#        env:
#          ANDROID_KEYS_SECRET_PASSPHRASE: ${{ secrets.android_secrets }}

      - name: Build ${{ inputs.build_type }}
        run: sh ./.github/scripts/android/build_android.sh
        env:
          BUILD_FLAVOR: ${{ inputs.build_flavor }}
          ANDROID_BUILD_TYPE: ${{ inputs.build_type }}
