name: 0_Analyze project code
on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
 analyze:
   runs-on: ubuntu-latest
   name: (${{ github.repository }}:${{ github.ref }}) Analyze project code
   steps:
     - uses: actions/checkout@v2
# send_message:
#   needs: [analyze]
#   runs-on: ubuntu-latest
#  - uses: appleboy/telegram-action@master
#    if: ${{ always() }}
#    name: Send message
#    with:
#    to: ${{ secrets.TELEGRAM_TO }}
#    token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
#    message: |
#      Action: ${{ github.workflow }}
#      Repository: ${{ github.repository }}
#      Branch:${{ github.ref }}
#      Status: ${{ job.status }}
#      Runner: ${{ runner.name }}
#      Link: ${{ github.server_url}}/${{ github.repository }}/actions/runs/${{ github.run_id }}
