name: 0_Send message
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: (${{ github.repository }}:${{ github.ref }}) CHECK_BOT
    steps:
      - name: send default message
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          message: Hello world