on:
  workflow_call:
    inputs:
      flavor:
        description: 'prod or dev'
        required: true
        type: string
        default: dev
      release_notes:
        required: false
        description: 'Release Note'
        type: string
    secrets:
      app_bundle_id:
        description: 'app_bundle_id'
        required: true
      provisioning_profile_specifier:
        description: 'provisioning_profile_specifier'
        required: true
      app_store_connect_team_id:
        description: 'app_store_connect_team_id'
        required: true
      developer_app_id:
        description: 'developer_app_id'
        required: true
      developer_portal_team_id:
        description: 'developer_portal_team_id'
        required: true
      fastlane_apple_id:
        description: 'fastlane_apple_id'
        required: true
      fastlane_apple_application_specific_password:
        description: 'fastlane_apple_application_specific_password'
        required: true
      match_password:
        description: 'match_password'
        required: true
      git_authorization:
        description: 'git_authorization'
        required: true
      temp_keychain_password:
        description: 'temp_keychain_password'
        required: true
      temp_keychain_user:
        description: 'temp_keychain_user'
        required: true

jobs:
  deploy_ios:
    runs-on: [ self-hosted ]
    steps:
      - name: Read Flutter version
        uses: KJ002/read-yaml@1.5
        id: flutter_version
        with:
          file: './pubspec.yaml'
          key-path: '["environment","flutter"]'

      - name: Get Flutter
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: ${{ steps.flutter_version.outputs.data }}
          channel: 'stable'

      - name: Check flow
        run: sh ./.github/scripts/flutter_check_flow.sh

      - name: Build ios
        run: sh ./.github/scripts/ios/build_ios.sh
        env:
          BUILD_FLAVOR: ${{ inputs.flavor }}

      - name: Distribute to TestFligh
        run: sh ./.github/scripts/run_fastlane.sh
        env:
          platform: ios
          action: distribute_to_testflight
          release_notes: ${{ inputs.release_notes }}
          IPA_FILE_PATH: './Runner.ipa'
          CONFIGURATION: 'Release'
          WORKSPACE: 'Runner.xcworkspace'
          SCHEME: 'Runner'
          APP_BUNDLE_ID: ${{ secrets.app_bundle_id }}
          PROVISIONING_PROFILE_SPECIFIER: ${{ secrets.provisioning_profile_specifier }}
          APP_STORE_CONNECT_TEAM_ID: ${{ secrets.app_store_connect_team_id }}
          DEVELOPER_APP_ID: ${{ secrets.developer_app_id }}
          DEVELOPER_PORTAL_TEAM_ID: ${{ secrets.developer_portal_team_id }}
          FASTLANE_APPLE_ID: ${{ secrets.fastlane_apple_id }}
          FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD: ${{ secrets.fastlane_apple_application_specific_password }}
          MATCH_PASSWORD: ${{ secrets.match_password }}
          GIT_AUTHORIZATION: ${{ secrets.git_authorization }}
          TEMP_KEYCHAIN_PASSWORD: ${{ secrets.temp_keychain_password }}
          TEMP_KEYCHAIN_USER: ${{ secrets.temp_keychain_user }}
