name: labeler
on:
  pull_request:
    types: [opened, edited, closed, reopened, ready_for_review, synchronize]
jobs:
  labeler:
    runs-on: ubuntu-latest
    name: Label the PR size
    steps:
      - uses: actions/checkout@v3
      - name: Label Mastermind
        uses: Resnovas/label-mastermind@1.4.0-alpha.5
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}