on:
  pull_request:
    types: [opened,edited]
jobs:
  specific_review_requested:
    runs-on: [self-hosted]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run Labeler
        #if: success()
        uses: crazy-max/ghaction-github-labeler@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          yaml-file: .github/labels.yml
          skip-delete: false
          dry-run: false
          exclude: |
            help*
            *issue