name: labeler
on:
  pull_request:
    types: [opened, edited, closed, reopened, ready_for_review, synchronize]
jobs:
  labeler:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    name: Label the PR size
    steps:
      - uses: actions/checkout@v3
      - name: Run Labeler
        if: success()
        uses: crazy-max/ghaction-github-labeler@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          yaml-file: .github/labels.yml
          skip-delete: true
          dry-run: false
      - name: Label Mastermind
        uses: Resnovas/label-mastermind@1.4.0-alpha.5
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #https://github.com/marketplace/actions/labeler
      - uses: actions/labeler@v4
        name: File labels
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}