name: Analyze project code
on:
  workflow_dispatch:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    name: Test action
    steps:
      - uses: actions/checkout@v2
      - name: Commit message
        run: echo 'message:' ${{ github.event.head_commit.message }}
