# Distribute build to Firebase
name: Distribute to Firebase

on:
  workflow_dispatch:
  push:
    branches:
      - 'release/**'
    tags:
      - 'v.*'
      - 'prod'
      - 'firebase'
jobs:
  build:
    runs-on: [self-hosted]
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: "12.x"

      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '2.2'
          channel: "stable"

      - name: Check flow
        run: sh ./.github/scripts/flutter_check_flow.sh

      - name: Decrypt Android keys
        run: sh ./.github/scripts/android/decrypt_android_keys.sh
        env:
          ANDROID_KEYS_SECRET_PASSPHRASE: ${{ secrets.ANDROID_KEYS_SECRET_PASSPHRASE }}

      - name: Build apk
        run: sh ./.github/scripts/android/build_apk.sh
        env:
          BUILD_FLAVOR: prod

      - name: Distribute to firebase
        run: sh ./.github/scripts/firebase_distributor.sh
        env:
          firebase_app_id: ${{ secrets.FIREBASE_ANDROID_PROD_APP_ID }}
          firebase_token: ${{ secrets.FIREBASE_TOKEN }}
          file_path: build/app/outputs/apk/prod/release/app-prod-release.apk
          groups: inner