# Собираем apk и отправляем его в github
name: Distribute to Github

on:
  workflow_dispatch:
    inputs:
      build_type:
        description: 'apk or appbundle'
        required: true
        default: appbundle

jobs:
  distribute:
    name: Distribute to Github
    runs-on: ubuntu-latest
    steps:
      - uses: sna2021/flutter_ci_example/.github/actions/prepare_workflow.yml@main
      - uses: sna2021/flutter_ci_example/.github/actions/assamble_android.yml@main
        with:
          build_type: apk
          build_flavor: prod

      - name: Upload apk to Github
        if: ${{ github.event.inputs.build_type == 'apk' }}
        uses: actions/upload-artifact@v1
        with:
          name: release-apk
          path: ./build/app/outputs/flutter-apk/app-prod-release.apk

      - name: Upload appbundle to Github
        if: ${{ github.event.inputs.build_type == 'appbundle' }}
        uses: actions/upload-artifact@v1
        with:
          name: release-aab
          path: ./build/app/outputs/bundle/prodRelease/app-prod-release.aab