name: Check
on:
  workflow_dispatch:
    # Enable manual run
    inputs:
      lane:
        description: 'Fastlane lane to use (beta OR promote_to_production OR production)'
        required: true
        default: 'beta'
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  fastlane-deploy:
    runs-on: [self-hosted]
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Install Fastlane
        run: |
          brew update
          brew install fastlane
