name: Get version
on:
  workflow_dispatch:

jobs:
  test-yaml-reader:
    runs-on: ubuntu-latest
    name: Test read-yaml
    steps:
      - uses: actions/checkout@v1
      - name: Run read-yaml action
        id: var
        with:
          file: './pubspec.yaml'
          key-path: '["version"]'

      - name: Get read-yaml output
        run: echo "${{ steps.var.outputs.data }}"
