name: [ STAGE ] Distribute ios to TestFlight
on:
  workflow_dispatch:
    inputs:
      flavor:
        # appbundle доступен если в Firebase Distribution настроен Service Account для GP
        description: '(dev или prod)'
        required: true
        default: dev
      release_notes:
        description: 'Описание для сборки'
        required: true
        default: ''
jobs:
  distribute_to_firebase:
    name: Distribute IOS to TestFlight [STAGE]
    uses: smmarty/maxidom_mobile/.github/workflows/_distribute_ios_to_test_flight.yaml.yml@main
    with:
      flavor: ${{ github.event.inputs.flavor}}
      release_notes: ${{ github.event.inputs.release_notes }}
    secrets:
      app_bundle_id: ${{ secrets.STAGE_APP_BUNDLE_ID }}
      provisioning_profile_specifier: ${{ secrets.STAGE_PROVISIONING_PROFILE_SPECIFIER }}
      app_store_connect_team_id: ${{ secrets.APP_STORE_CONNECT_TEAM_ID }}
      developer_app_id: ${{ secrets.FASTLANE_APPLE_ID }}
      developer_portal_team_id: ${{ secrets.DEVELOPER_PORTAL_TEAM_ID }}
      fastlane_apple_id: ${{ secrets.FASTLANE_APPLE_ID }}
      fastlane_apple_application_specific_password: ${{ secrets.FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD }}
      match_password: ${{ secrets.MATCH_PASSWORD }}
      git_authorization: ${{ secrets.GIT_AUTHORIZATION }}
      temp_keychain_password: ${{ secrets.TEMP_KEYCHAIN_PASSWORD }}
      temp_keychain_user: ${{ secrets.TEMP_KEYCHAIN_USER }}

