name: _Workflow 1

on:
  workflow_call:
    inputs:
      input_data:
        required: true
        type: string
jobs:
  build:
    name: workflow 1
    runs-on: [ self-hosted ]
    steps:
      - name: Run script 1
        run: sh ./.github/scripts/script_1.sh
